[versions]
fabric_loom = "1.10-SNAPSHOT"
minotaur = "2.+"
shadow = "9.0.0-beta7"

minecraft = "1.20.1"
yarn = "1.20.1+build.10"

fabric_loader = "0.16.14"
fabric_api = "0.87.0+1.20.1"

kaleido = "0.3.3+1.3.2"

jda = "5.5.1"
discord-webhooks = "0.8.4"

styled-chat = "pwr7uYCH"
pb4-api-predicate = "0.2.1+1.20.1"
pb4-api-placeholder = "2.1.4+1.20.1"
pb4-api-playerdata = "0.2.2+1.19.3"
fabric-permissions = "0.2-SNAPSHOT"

[plugins]
fabric_loom = { id = "fabric-loom", version.ref = "fabric_loom" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }

[libraries]
minecraft = { group = "mojang", name = "minecraft", version.ref = "minecraft" }
yarn = { group = "net.fabricmc", name = "yarn", version.ref = "yarn" }

fabric_loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric_loader" }
fabric_api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric_api" }

kaleido = { group = "folk.sisby", name = "kaleido-config", version.ref = "kaleido" }

jda = { group = "net.dv8tion", name = "JDA", version.ref = "jda" }
discordwebhooks = { group = "club.minnced", name = "discord-webhooks", version.ref = "discord-webhooks" }

styled-chat = { module = "maven.modrinth:styled-chat", version.ref = "styled-chat" }
pb4-api-predicate = { module = "eu.pb4:predicate-api", version.ref = "pb4-api-predicate" }
pb4-api-placeholder = { module = "eu.pb4:placeholder-api", version.ref = "pb4-api-placeholder" }
pb4-api-playerdata = { module = "eu.pb4:player-data-api", version.ref = "pb4-api-playerdata" }
fabric-permissions = { module = "me.lucko:fabric-permissions-api", version.ref = "fabric-permissions" }
